/* tslint:disable */
/* eslint-disable */
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetHealth429Response } from '../models';
// @ts-ignore
import type { GetV1RunnerModels200Response } from '../models';
// @ts-ignore
import type { PostV1RunnerChat200Response } from '../models';
// @ts-ignore
import type { PostV1RunnerChatRequest } from '../models';
// @ts-ignore
import type { PostV1RunnerGenerateRequest } from '../models';
/**
 * RunnerApi - axios parameter creator
 */
export const RunnerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List configured runner model routes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1RunnerModels: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/runner/models`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Multi-turn chat completion
         * @param {PostV1RunnerChatRequest} postV1RunnerChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1RunnerChat: async (postV1RunnerChatRequest: PostV1RunnerChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postV1RunnerChatRequest' is not null or undefined
            assertParamExists('postV1RunnerChat', 'postV1RunnerChatRequest', postV1RunnerChatRequest)
            const localVarPath = `/v1/runner/chat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postV1RunnerChatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Single-prompt generation
         * @param {PostV1RunnerGenerateRequest} postV1RunnerGenerateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1RunnerGenerate: async (postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postV1RunnerGenerateRequest' is not null or undefined
            assertParamExists('postV1RunnerGenerate', 'postV1RunnerGenerateRequest', postV1RunnerGenerateRequest)
            const localVarPath = `/v1/runner/generate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postV1RunnerGenerateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RunnerApi - functional programming interface
 */
export const RunnerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RunnerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List configured runner model routes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1RunnerModels(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetV1RunnerModels200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1RunnerModels(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunnerApi.getV1RunnerModels']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Multi-turn chat completion
         * @param {PostV1RunnerChatRequest} postV1RunnerChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostV1RunnerChat200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1RunnerChat(postV1RunnerChatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunnerApi.postV1RunnerChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Single-prompt generation
         * @param {PostV1RunnerGenerateRequest} postV1RunnerGenerateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostV1RunnerChat200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1RunnerGenerate(postV1RunnerGenerateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunnerApi.postV1RunnerGenerate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RunnerApi - factory interface
 */
export const RunnerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RunnerApiFp(configuration)
    return {
        /**
         * 
         * @summary List configured runner model routes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1RunnerModels(options?: RawAxiosRequestConfig): AxiosPromise<GetV1RunnerModels200Response> {
            return localVarFp.getV1RunnerModels(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Multi-turn chat completion
         * @param {PostV1RunnerChatRequest} postV1RunnerChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<PostV1RunnerChat200Response> {
            return localVarFp.postV1RunnerChat(postV1RunnerChatRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Single-prompt generation
         * @param {PostV1RunnerGenerateRequest} postV1RunnerGenerateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest, options?: RawAxiosRequestConfig): AxiosPromise<PostV1RunnerChat200Response> {
            return localVarFp.postV1RunnerGenerate(postV1RunnerGenerateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RunnerApi - interface
 */
export interface RunnerApiInterface {
    /**
     * 
     * @summary List configured runner model routes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getV1RunnerModels(options?: RawAxiosRequestConfig): AxiosPromise<GetV1RunnerModels200Response>;

    /**
     * 
     * @summary Multi-turn chat completion
     * @param {PostV1RunnerChatRequest} postV1RunnerChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<PostV1RunnerChat200Response>;

    /**
     * 
     * @summary Single-prompt generation
     * @param {PostV1RunnerGenerateRequest} postV1RunnerGenerateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest, options?: RawAxiosRequestConfig): AxiosPromise<PostV1RunnerChat200Response>;

}

/**
 * RunnerApi - object-oriented interface
 */
export class RunnerApi extends BaseAPI implements RunnerApiInterface {
    /**
     * 
     * @summary List configured runner model routes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getV1RunnerModels(options?: RawAxiosRequestConfig) {
        return RunnerApiFp(this.configuration).getV1RunnerModels(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Multi-turn chat completion
     * @param {PostV1RunnerChatRequest} postV1RunnerChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest, options?: RawAxiosRequestConfig) {
        return RunnerApiFp(this.configuration).postV1RunnerChat(postV1RunnerChatRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Single-prompt generation
     * @param {PostV1RunnerGenerateRequest} postV1RunnerGenerateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest, options?: RawAxiosRequestConfig) {
        return RunnerApiFp(this.configuration).postV1RunnerGenerate(postV1RunnerGenerateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

