/* tslint:disable */
/* eslint-disable */
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetV1RunnerModels200ResponseData } from './get-v1-runner-models200-response-data';
// May contain unused imports in some cases
// @ts-ignore
import type { Meta } from './meta';

export interface GetV1RunnerModels200Response {
    'data'?: GetV1RunnerModels200ResponseData;
    'error'?: Error;
    'meta'?: Meta;
    'success': boolean;
}

