/* tslint:disable */
/* eslint-disable */
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PostV1RunnerChatRequestMessagesInner } from './post-v1-runner-chat-request-messages-inner';

export interface PostV1RunnerChatRequest {
    'messages': Array<PostV1RunnerChatRequestMessagesInner>;
}

